version: '3.9'
services:
  database:
    image: postgres:14.3
    restart: on-failure
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backups:/backups
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  backend:
    image: backend
    depends_on:
      - database
      - redis
      - celery_worker
      - celery_scheduler
    command: "/sbin/init"
    build:
      context: app
      dockerfile: Dockerfile
      args:
        DEBUG: ${DEBUG}
        PROJECT_NAME: ${PROJECT_NAME}
        SERVER_NAME: ${SERVER_NAME}
        PROJECT_DESCRIPTION: ${PROJECT_DESCRIPTION}
        APP_PORT: ${APP_PORT}
        VERSION: ${VERSION}
        PRETRAINED_MODEL_CACHE_DIR: ${PRETRAINED_MODEL_CACHE_DIR}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        REDIS_HOST: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASSWORD: ${REDIS_PASSWORD}

    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./.models:/app/${PRETRAINED_MODEL_CACHE_DIR}
    privileged: true

  redis:
    image: redis
    restart: on-failure
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  celery_worker:
    image: backend
    command: celery worker -A workers.core worker -l INFO -f logs/celery_worker.log --concurrency 4
    depends_on:
      - database
      - redis
    volumes:
      - ./logs:/app/logs

  celery_scheduler:
    image: backend
    command: celery -A workers.core beat -l INFO --scheduler celery_sqlalchemy_scheduler:DatabaseScheduler -f logs/celery_scheduler.log
    depends_on:
      - database
      - redis
      - celery_worker
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local
  postgres_backups:
    driver: local
  redis_data:
    driver: local
