#!/bin/sh
cat << EOF
DEBUG=${DEBUG}
PROJECT_NAME=${PROJECT_NAME}
SERVER_NAME=${SERVER_NAME}
PROJECT_DESCRIPTION=${PROJECT_DESCRIPTION}
APP_PORT=${APP_PORT}
VERSION=${VERSION}
PRETRAINED_MODEL_CACHE_DIR=${PRETRAINED_MODEL_CACHE_DIR}
POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PORT=${POSTGRES_PORT}
EOF